
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url= ${DB_URL}
quarkus.hibernate-orm.schema-management.strategy=update


mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem
mp.jwt.verify.issuer=my-bank

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_URL}
quarkus.http.cors.methods=GET,POST,PUT
quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}